class Difficulty(type):
    class EASY(Difficulty): ...
    class MEDIUM(Difficulty): ...
    class HARD(Difficulty): ...

SudokuType = list[int]

def generate_sudoku() -> SudokuType:
    ...

def generate_sudoku_with_difficulty(difficulty: Difficulty) -> SudokuType:
    ...